drop table if exists expenditure CASCADE;
create table expenditure
(
    id       bigint generated by default as identity,
    category varchar(10),
    title    varchar(20),
    detail   varchar(50),
    expenditure_value    bigint,
    expenditure_date     date,
    payment  varchar(10),
    primary key (id)
);